image:
  file: .gitpod.Dockerfile

tasks:
- name: install squashfuse and fuse
  command: sudo install-packages squashfuse fuse
- name: enable singularity
  command: singularity shell --sif-fuse docker://python:3.8.9-slim

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
